### PR TITLE
Item view width

### PR DESCRIPTION
**Pull request by emiliodeg**
Get little more width in lg screen

### CODE REVIEW

**Comment by sergeyklay** [comment]
Hello @emiliodeg 

Thank you for your patch, and for helping us make Phalcon Docs site better. Unfortunately, we can't accept this PR  because it contradicts the intended goals and negatively affects the current layout. 

Could you please explain a bit more what you try to fix/improve.

// cc @Spurius96

**Comment by niden** [comment]
@emiliodeg Do we need to keep this open?

**Comment by emiliodeg** [comment]
sure you can close this. Is the same change you did here in #87

**Comment by niden** [comment]
Thank you

**Pull request closed without merging**
