### PR TITLE
change from http to https v3

### PR DESCRIPTION
**Pull request by Arhell**
issue #240

### CODE REVIEW

**Comment by Jeckerson** [comment]
```
10:58:13 AM:      Build Warning: Layout 'デフォルト' requested in 4.0/ja-jp/api/index.md does not exist.
11:00:42 AM:   Liquid Exception: Could not locate the included file 'sponsors.html' in any of ["/opt/build/repo/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in 4.0/nl-nl/sponsors.md
```

**Comment by niden** [comment]
> Please do not modify translation. You have to change only original language (English)

For 3.4 it is OK to change translations.

My only concern is that we test that the link is correct before changing it.

**Comment by sergeyklay** [comment]
@Arhell Could you check build logs? It seems deploy is failed. Also what do you think about creating a loop through the list of changed links and checking each link?

**Comment by Arhell** [comment]
> @Arhell Could you check build logs? It seems deploy is failed. Also what do you think about creating a loop through the list of changed links and checking each link?

Hi @sergeyklay 
I checked all the links when I did this
Have a question
1. https://vokuro.phalcon.io does not work
2. https://jinja.pocoo.org/ gives an error but http://jinja.pocoo.org/ is not present, remove "s"?
3. deploy is failed @niden maybe need to update documents?

**Comment by sergeyklay** [comment]
1. @niden Could you please help use here
2. Yes
3. /cc @niden

**Pull request merged**
