### PR TITLE
Added a small margin bottom to improve reading

### PR DESCRIPTION
**Pull request by emiliodeg**
This improve reading
Just only add 15px of bottom margin at children of .article-content

### CODE REVIEW

**Comment by ninjapanzer** [comment]
@emiliodeg do you mind using `em` I am trying to migrate to relative units when I make changes.

**Comment by emiliodeg** [comment]
yeah even better than em's is rem's but what I have seen in stylesheets all margins in px I try to continues the rule

**Comment by niden** [comment]
Thank you!!

**Pull request merged**
