### PR TITLE
Spanish translation of the Filter cartoon

### PR DESCRIPTION
**Pull request by diplopito**
Made an "es-es" subfolder to organize assets according to language.

### CODE REVIEW

**Comment by niden** [comment]
@diplopito  Where is the readme used?. Also I was thinking about this over the weekend after our discussion in discord. I don't think the image will change since crowdin will replace it with the source one.

**Comment by diplopito** [comment]
Readme: I used it only to create the folder and upload there the file, it can be deleted now.
Regarding the image: I can ask the Crowdin team to see what do they suggest, what do you think about it?

**Comment by CameronHall** [comment]
> I can ask the Crowdin team to see what do they suggest, what do you think about it?
@diplopito if you could that'd be great :) Let us know what they get back to you with.

**Comment by niden** [comment]
This will require the cartoon file to be introduced in the documentation itself vs the docs-app. We are not going to do this because it opens the door to unnecessary maintenance.

**Pull request closed without merging**
