### PR TITLE
[WIP] Don't throw an uncaught exception on 404

### PR DESCRIPTION
**Pull request by ninjapanzer**

### CODE REVIEW

**Comment by niden** [comment]
Thank you!

**Comment by sergeyklay** [comment]
@ninjapanzer The 
```php
(new Dotenv\Dotenv(dirname(__DIR__)))->load();
```
may throw `InvalidPathException`. For more see:
https://github.com/vlucas/phpdotenv/blob/master/src/Loader.php#L95-L100

In my opinion better way is to use here: 
```php
(new Dotenv\Dotenv(dirname(__DIR__)))->safeLoad();
```
without  `try/catch` at all. See:
https://github.com/vlucas/phpdotenv/blob/master/src/Dotenv.php#L58-L66

But actually I'm more interested in `Docs\Exception\HttpException`. I'm pretty sure there is no `HttpException` here because `.env` file doesn't exist. Could you please elaborate on that?

**Comment by ninjapanzer** [comment]
That makes sense, though I am catching https://github.com/phalcon/docs-app/blob/master/app/controllers/DocsController.php#L61-L63

**Comment by ninjapanzer** [comment]
You are absolutely right I have no idea what is happening here

**Pull request merged**
